### ISSUE TITLE
As Dr. Bob, it would be very helpful in my role as researcher, to be able to export the data into an Excel usable format

### ISSUE THREAD

**Issue by jodimward** [esridc/openfda#38]
### Tasks

- [x] Implement with Koop @dmfenton
[live](http://koop-fda-1504637322.us-east-1.elb.amazonaws.com/FDA.csv)
- [x] Design download button @michaelgaigg 
- [ ] Integrate download button

**Comment by dmfenton** [comment]
done: visit http://koop.dc.esri.com/FDA.csv to download.
working on getting this in Docker on AWS. I'll use #27 to track progress.

**Comment by dmfenton** [comment]
We need to have a download button in the UI somewhere or else this feature cannot be used.

**Comment by dmfenton** [comment]
@michaelgaigg can you do a simple mock up of where the download button should go?

**Comment by michaelgaigg** [comment]
which data needs to be downloaded?

**Comment by dmfenton** [comment]
The same things that are being viewed in the table. For example, dangerous recalls in the last 6 months.

**Comment by dmfenton** [comment]
E.g. here I should get 1007 rows
![image](https://cloud.githubusercontent.com/assets/7832202/8418573/24c7767a-1e82-11e5-997c-6dba0e774b4d.png)

**Comment by michaelgaigg** [comment]
add a button that allows for downloading the data

![uploads/4daf2556-8f31-4fa9-99ce-1357c7a89779/download_data.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4daf2556-8f31-4fa9-99ce-1357c7a89779%2Fdownload_data.JPG)

**Comment by benheb** [comment]
Done!

**Comment by jodimward** [comment]
@benheb looks good!!! Dr. Bob thanks you :)

**Comment by benheb** [comment]
:+1: :+1:
